// Generated by Wrangler by running `wrangler types`
// After wrangler types, manually add environment variables

interface Env {
  // Cloudflare Bindings (auto-generated)
  DB: D1Database;
  STORAGE: R2Bucket;
  VECTOR_INDEX: VectorizeIndex;
  INGEST_QUEUE: Queue;
  INGEST_DLQ: Queue;
  AI: Ai;

  // Environment Variables (manually added)
  API_TOKEN: string;
  ARXIV_CATEGORIES: string;
}
