/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as PapersRouteImport } from "./routes/papers";
import { Route as ArxivRouteImport } from "./routes/arxiv";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PapersIdRouteImport } from "./routes/papers.$id";

const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const PapersRoute = PapersRouteImport.update({
  id: "/papers",
  path: "/papers",
  getParentRoute: () => rootRouteImport,
} as any);
const ArxivRoute = ArxivRouteImport.update({
  id: "/arxiv",
  path: "/arxiv",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const PapersIdRoute = PapersIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => PapersRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/arxiv": typeof ArxivRoute;
  "/papers": typeof PapersRouteWithChildren;
  "/search": typeof SearchRoute;
  "/papers/$id": typeof PapersIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/arxiv": typeof ArxivRoute;
  "/papers": typeof PapersRouteWithChildren;
  "/search": typeof SearchRoute;
  "/papers/$id": typeof PapersIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/arxiv": typeof ArxivRoute;
  "/papers": typeof PapersRouteWithChildren;
  "/search": typeof SearchRoute;
  "/papers/$id": typeof PapersIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/arxiv" | "/papers" | "/search" | "/papers/$id";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/arxiv" | "/papers" | "/search" | "/papers/$id";
  id: "__root__" | "/" | "/arxiv" | "/papers" | "/search" | "/papers/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ArxivRoute: typeof ArxivRoute;
  PapersRoute: typeof PapersRouteWithChildren;
  SearchRoute: typeof SearchRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/papers": {
      id: "/papers";
      path: "/papers";
      fullPath: "/papers";
      preLoaderRoute: typeof PapersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/arxiv": {
      id: "/arxiv";
      path: "/arxiv";
      fullPath: "/arxiv";
      preLoaderRoute: typeof ArxivRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/papers/$id": {
      id: "/papers/$id";
      path: "/$id";
      fullPath: "/papers/$id";
      preLoaderRoute: typeof PapersIdRouteImport;
      parentRoute: typeof PapersRoute;
    };
  }
}

interface PapersRouteChildren {
  PapersIdRoute: typeof PapersIdRoute;
}

const PapersRouteChildren: PapersRouteChildren = {
  PapersIdRoute: PapersIdRoute,
};

const PapersRouteWithChildren = PapersRoute._addFileChildren(PapersRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArxivRoute: ArxivRoute,
  PapersRoute: PapersRouteWithChildren,
  SearchRoute: SearchRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
